liste = ['Schwalbe', 'Kokosnuss', 13, 'Spam', 3.14]
liste.append('Ni')
liste.extend([4, 5, 3.14])
liste.insert(2, 'Taube')
print(liste.count(3.14))
print(liste)
print(liste.index(3.14))
liste.remove(3.14)
print(liste)
liste.pop(2)
print(liste)
liste.reverse()
print(liste)
print(sum([1, 3, 5]))
